version: '3.8'

services:
  pkuautoelective:
    image: tim44/pkuautoelective-docker:latest
    container_name: pkuautoelective
    volumes:
      - ~/Container/PKUAutoElective-docker/config:/PKUAutoElective/PAE_private/config
      - ~/Container/PKUAutoElective-docker/keys:/PKUAutoElective/PAE_private/keys
      - ~/Container/PKUAutoElective-docker/logs:/PKUAutoElective/logs
      - ~/Container/PKUAutoElective-docker/pkuautoelective.sh:/PKUAutoElective/pkuautoelective.sh
    network_mode: host
